<a href="https://colab.research.google.com/github/kahmed92/AI-Q2-learning-resources/blob/master/A1_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment For Numpy
Difficulty Level **Beginner**

Import the numpy package under the name np

In [ ]:
import numpy as np

**Question:**
Create a null vector of size 10

In [ ]:
x=np.zeros(10)

**Question:**
Create a vector with values ranging from 10 to 49

In [ ]:
y=np.arange(10,50)

**Question: **
Find the shape of previous array in question 3

In [ ]:
y.shape

(40,)

**Question:**
Print the type of the previous array in question 3

In [ ]:
y.astype

<function ndarray.astype>

**Question:**
Print the numpy version and the configuration

In [ ]:
print(np.__version__)

1.19.4


**Question:**
Print the dimension of the array in question 3

In [ ]:
y.ndim

1

**Question:**
Create a boolean array with all the True values

In [ ]:
z=np.ones(2,dtype=bool)

**Question:**
Create a two dimensional array

In [ ]:
import numpy as np
x=np.arange(2,2)

**Question:**
Create a three dimensional array

In [ ]:
y=np.arange(2,2,2)

Difficulty Level **Easy**

**Question:**

Reverse a vector (first element becomes last)

In [53]:
z=np.arange(50)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [56]:
z=z[::-1]
z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

**Question:**
Create a null vector of size 10 but the fifth value which is 1

In [ ]:
x=np.eye(10)[4]
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**Question:**
Create a 3x3 identity matrix

In [ ]:
y=np.eye(3)
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Question:**
arr = np.array([1, 2, 3, 4, 5])

Convert the data type of the given array from int to float

In [57]:
arr = np.array([1, 2, 3, 4, 5])
arr=np.asarray(arr,dtype=float)
arr

array([1., 2., 3., 4., 5.])

**Question:**
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
Multiply arr1 with arr2

In [ ]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr3 = arr1 * arr2

**Question:**
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
Make an array by comparing both the arrays provided above

In [ ]:
arr3=(arr1==arr2)
arr3

array([[False, False, False],
       [False, False, False]])

**Question:**
Extract all odd numbers from arr with values(0-9)

In [ ]:
arr=np.arange(0,10)
ao=(arr[arr%2==1])
ao

array([1, 3, 5, 7, 9])

**Question:**
Replace all odd numbers to -1 from previous array

In [ ]:
aa=(ao/ao)*-1
aa

array([-1., -1., -1., -1., -1.])

**Question:**
arr = np.arange(10)
Replace the values of indexes 5,6,7 and 8 to 12

In [ ]:
arr = np.arange(10)
arr[-5:-1]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

**Question:**
Create a 2d array with 1 on the border and 0 inside

In [ ]:
arr=np.ones((4,4))
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

**Question:**
Difficulty Level **Medium**

arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
Replace the value 5 to 12

In [ ]:
arr2d = np.array([[1, 2, 3],
            [4, 5, 6], 
            [7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

**Question:**
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
Convert all the values of 1st array to 64

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0,:]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

**Question:**
Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [ ]:
arr2d = np.arange(9).reshape(3,3)
arr2d[0:1]

array([[0, 1, 2]])

**Question:**
Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [ ]:
arr2d = np.arange(9).reshape(3,3)
arr2d[1:2]

array([[3, 4, 5]])

**Question:**
Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [58]:
arr2d = np.arange(9).reshape(3,3)
arr2d[0:2,2:3]

array([[2],
       [5]])

**Question:**
Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
arr2d = np.arange(100).reshape(10,10)
arr2d.max()


99

In [ ]:
arr2d.min()


0

**Question:**
a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
Find the common items between a and b

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


**Question:**
a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
Find the positions where elements of a and b match

In [ ]:
np.where(np.in1d(a,b))[0]

array([1, 3, 5, 7])

**Question:**
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 

data = np.random.randn(7, 4)

Find all the values from array data where the values from array names are not equal to Will and Joe

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
fil = (names == 'Will') | (names == 'Joe')
fil
data[fil]

array([[ 0.28650564,  3.17786839, -0.64451151, -1.15794374],
       [ 0.81610452, -1.90129329, -2.17654663, -0.14052631],
       [ 1.0393915 ,  0.65248512,  0.96375936,  0.1910044 ],
       [ 1.64779498,  0.29191295,  0.65347176,  0.54530411],
       [-0.91494141,  0.04036231, -2.84296464,  1.01631811]])

**Question:**
Difficulty Level **Hard**

Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [ ]:
arr=np.arange(15).reshape(5,3)+np.random.randn(5,3)
arr

array([[-0.03886634,  1.56799421,  2.43889758],
       [ 4.27029562,  0.57605481,  5.06542998],
       [ 5.90867498,  8.30826402,  6.85277096],
       [10.57592959, 10.32202716, 10.40407658],
       [13.13595304, 13.72925872, 13.6404918 ]])

**Question**
Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [11]:
a_3d_array = np.arange(16).reshape(2, 2, 4) + np.random.rand(2,2,4)
print(a_3d_array)

[[[ 0.1777643   1.32752969  2.69806142  3.99642666]
  [ 4.53479939  5.56343612  6.08685196  7.70584385]]

 [[ 8.82510723  9.29501621 10.60270085 11.79404602]
  [12.3843939  13.20464751 14.35260253 15.09570811]]]


**Question:**
Swap axes of the array you created in Question 32

In [16]:
a_3d_array=np.swapaxes(a_3d_array,2,1)
print(a_3d_array)

[[[ 0.1777643   4.53479939]
  [ 1.32752969  5.56343612]
  [ 2.69806142  6.08685196]
  [ 3.99642666  7.70584385]]

 [[ 8.82510723 12.3843939 ]
  [ 9.29501621 13.20464751]
  [10.60270085 14.35260253]
  [11.79404602 15.09570811]]]


**Question:**
Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [24]:
arr=np.arange(10) ** 0.5
arr[arr<0.5]=0
print(arr)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


**Question:**
Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [9]:
arr1=np.arange(np.random.randint(12))
arr2=np.arange(np.random.randint(12))
arr1


array([0, 1, 2, 3, 4, 5])

In [10]:
arr2

array([0, 1, 2])

In [12]:
arr3=np.append(arr1,arr2)
np.max(arr3)


5

**Question:**
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
**Find the unique names and sort them out!**

In [13]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

**Question:** 
a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])
**From array a remove all items present in array b**

In [15]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

**Question:**
Following is the input NumPy array delete column two and insert following new column in its place.

sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = numpy.array([[10,10,10]])

In [39]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray=np.append(sampleArray,newColumn,axis=0)
sampleArray=np.delete(sampleArray,2,0)
np.transpose(sampleArray)

array([[34, 82, 10],
       [43, 22, 10],
       [73, 12, 10]])

**Question:**
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 

y = np.array([[6., 23.], [-1, 7], [8, 9]])

Find the dot product of the above two matrix


In [43]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

**Question:**
Generate a matrix of 20 random values and find its cumulative sum

In [52]:
arr=np.arange(20).reshape(4,5)
arr=arr*np.random.randint(20)
np.sum(arr)

1140