<a href="https://colab.research.google.com/github/kahmed92/AI-Q2-learning-resources/blob/master/A2_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy_Assignment_2::
**Question:1**
Convert a 1D array to a 2D array with 2 rows?
Desired output::

array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

In [33]:
import numpy as np

In [4]:
arr=np.arange(10)
arr=arr.reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**Question:2**
How to stack two arrays vertically?

Desired Output::

array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

In [7]:
arr1=np.arange(10).reshape(2,5)
arr2=np.ones((2,5))
arr3=np.append(arr1,arr2,axis=0)
arr3

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**Question:3**
How to stack two arrays horizontally?

Desired Output::

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [8]:
arr1=np.arange(10).reshape(2,5)
arr2=np.ones((2,5))
arr3=np.append(arr1,arr2,axis=1)
arr3

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.],
       [5., 6., 7., 8., 9., 1., 1., 1., 1., 1.]])

**Question:4**
How to convert an array of arrays into a flat 1d array?

Desired Output::

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr1=np.arange(10).reshape(2,5)
arr1.reshape(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Question:5**
How to Convert higher dimension into one dimension?

Desired Output::

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [15]:
arr1=np.arange(15).reshape(3,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
arr1.reshape(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**Question:6**
Convert one dimension to higher dimension?

Desired Output::

array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11], [12, 13, 14]])

In [18]:
arr1=np.arange(15)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
arr1.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

**Question:7**
Create 5x5 an array and find the square of an array?

In [21]:
arr1=np.arange(25).reshape(5,5)
np.square(arr1)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

**Question:8**
Create 5x6 an array and find the mean?

In [24]:
arr1=np.arange(30).reshape(5,6)
np.mean(arr1)

14.5

**Question:9**
Find the standard deviation of the previous array in Q8?

In [25]:
np.std(arr1)

8.65544144839919

**Question:10**
Find the median of the previous array in Q8?

In [26]:
np.median(arr1)

14.5

**Question:11**
Find the transpose of the previous array in Q8?

In [27]:
np.transpose(arr1)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

**Question:12**
Create a 4x4 an array and find the sum of diagonal elements?

In [31]:
arr2=np.arange(16).reshape(4,4)
np.sum(arr2*np.eye(4))

30.0

**Question:13**
Find the determinant of the previous array in Q12?

In [32]:
arr2=np.arange(16).reshape(4,4)
arr2=arr2*np.eye(4)
np.linalg.det(arr2)

0.0

**Question:14**
Find the 5th and 95th percentile of an array?

In [34]:
arr=np.arange(16).reshape(4,4)
np.percentile(arr,5)

0.75

In [35]:
np.percentile(arr,95)

14.25

**Question:15**
How to find if a given array has any null values?

In [36]:
arr=np.arange(10)
np.isnan(arr)

array([False, False, False, False, False, False, False, False, False,
       False])